### ISSUE TITLE
Teminal mode still switched with "a"

### ISSUE THREAD

**Issue by stefanhaustein** [stefanhaustein/empire#2]
Leftover from "Anzeige"?

**Comment by stefanhaustein** [comment]
Still reproducible on the server O:)

**Comment by pleumann** [comment]
Deployments only during the weekend! 😁

Stefan Haustein <notifications@github.com> schrieb am Sa., 4. Juli 2020,
01:43:

**Comment by pleumann** [comment]
Done.
